package com.aegis.aegis_server.service;

import com.aegis.aegis_server.domain.AdminUser;
import com.aegis.aegis_server.repository.AdminUserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Runs once on startup to ensure the default admin user exists with the correct
 * BCrypt-hashed password. This is more reliable than a hardcoded SQL hash in
 * a Flyway migration, because the hash is generated by Spring's own PasswordEncoder.
 *
 * Default credentials: admin / admin123
 * Change the password after first login in production!
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class AdminDataInitializer implements ApplicationRunner {

    private static final String DEFAULT_USERNAME = "admin";
    private static final String DEFAULT_PASSWORD = "admin123";

    private final AdminUserRepository adminUserRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        adminUserRepository.findByUsername(DEFAULT_USERNAME).ifPresentOrElse(
            admin -> {
                // If the hash doesn't match the default password, fix it.
                // (Handles the case where the Flyway seed had a wrong/stale hash)
                if (!passwordEncoder.matches(DEFAULT_PASSWORD, admin.getPassword())) {
                    log.warn("[Aegis] Default admin password hash mismatch — resetting to default");
                    admin.setPassword(passwordEncoder.encode(DEFAULT_PASSWORD));
                    adminUserRepository.save(admin);
                    log.info("[Aegis] Admin password reset to default: {}/{}", DEFAULT_USERNAME, DEFAULT_PASSWORD);
                } else {
                    log.info("[Aegis] Default admin user OK (username: {})", DEFAULT_USERNAME);
                }
            },
            () -> {
                // No admin user found at all — create one from scratch
                AdminUser admin = AdminUser.builder()
                        .username(DEFAULT_USERNAME)
                        .password(passwordEncoder.encode(DEFAULT_PASSWORD))
                        .role("ADMIN")
                        .build();
                adminUserRepository.save(admin);
                log.info("[Aegis] Created default admin user: {}/{}", DEFAULT_USERNAME, DEFAULT_PASSWORD);
            }
        );
    }
}
